=== rafaelMunoz77/LMSGI_2022-23/Unidad_04_DTD_XSD/DTD/exámenes antiguos/DTD2018/Harry Potter/examen.dtd
<!ELEMENT harryPotter (#PCDATA | casa | pelicula)*>
<!ELEMENT pelicula (titulo, (secuela | precuela))>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT secuela (#PCDATA)>
<!ELEMENT precuela (#PCDATA)>
<!ATTLIST pelicula personajes IDREFS #REQUIRED>
<!ENTITY harry "Me encanta Harry Potter">
<!ENTITY % atributoEdad "edad (infantil | adolescente | adulto) 'infantil'">
<!ATTLIST harryPotter %atributoEdad;>
<!ELEMENT casa (personaje+)>
<!ATTLIST casa nombre ID #IMPLIED>
<!ELEMENT personaje EMPTY>
<!ATTLIST personaje nombre ID #REQUIRED 
                    %atributoEdad;
                    estado (muerto | vivo) #FIXED "vivo"
                    antagonista IDREF #IMPLIED>

=== rafaelMunoz77/LMSGI_2022-23/Unidad_04_DTD_XSD/DTD/exámenes antiguos/DTD2018/Harry Potter/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE harryPotter SYSTEM "examen.dtd">
<harryPotter edad="infantil">&harry;
	<casa nombre="Griffyndor">
		<personaje nombre="Ron" edad="infantil" estado="vivo" antagonista="Malfoy"/>
		<personaje nombre="Hermione" edad="infantil" estado="vivo"/>
		<personaje nombre="Malfoy" edad="infantil" estado="vivo"/>
	</casa>
	<pelicula personajes="Ron Hermione">
		<titulo>La piedra filosofal</titulo>
		<secuela>La cámara secreta</secuela>
	</pelicula>
</harryPotter>
