=== rafaelMunoz77/LMSGI_2022-23/Unidad_04_DTD_XSD/DTD/exámenes antiguos/DTD2018/Karate Kid/examen.dtd
<!ELEMENT pelicula (#PCDATA | personaje | parte)*>
<!ENTITY % atributoNombre "nombre (California | Tokio | Japon) 'California'">
<!ELEMENT personaje EMPTY>
<!ATTLIST personaje nombre ID #REQUIRED 
                    enemigo IDREF #IMPLIED
                    relacionCon IDREFS #IMPLIED
                    rol CDATA #FIXED "sensei">
<!ELEMENT parte (nombre, (escenario | pais), puntuacion?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT puntuacion (valoracion+)>
<!ELEMENT valoracion (#PCDATA)>
<!ELEMENT escenario EMPTY>
<!ATTLIST escenario %atributoNombre;>
<!ELEMENT pais EMPTY>
<!ATTLIST pais %atributoNombre;>
<!ENTITY okinawa "Un lugar precioso">

=== rafaelMunoz77/LMSGI_2022-23/Unidad_04_DTD_XSD/DTD/exámenes antiguos/DTD2018/Karate Kid/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicula SYSTEM "examen.dtd">
<pelicula>
	Karate Kid
	<personaje nombre="Alice" relacionCon="Daniel Johnny" />
	<personaje nombre="Daniel" enemigo="Johnny" />
	<personaje nombre="Johnny" enemigo="Daniel" />
	<personaje nombre="Miyagi" rol="sensei" />
	<parte>
		<nombre>I</nombre>
		<escenario nombre="California" />
		<puntuacion>
			<valoracion>Una web que le da un 9</valoracion>
			<valoracion>Una web que le da un 10</valoracion>
		</puntuacion>
	</parte>
	<parte>
		<nombre>II - &okinawa;</nombre>
		<pais nombre="Japon" />
		<puntuacion>
			<valoracion>Una web que le da un 9</valoracion>
			<valoracion>Una web que le da un 10</valoracion>
		</puntuacion>
	</parte>
</pelicula>
