=== rafaelMunoz77/LMSGI_2022-23/Unidad_04_DTD_XSD/XSD/examen2017/simpsons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="simpsons" type="tipoSimpsons"/>

    <xs:complexType name="tipoSimpsons">
        <xs:all>
            <xs:element name="personajes" type="tipoPersonajes"/>
            <xs:element name="mascota" type="tipoMascota"/>
            <xs:element name="capitulos" type="tipoCapitulos"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="tipoMascota">
        <xs:attribute name="nombre" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="tipoPersonaje">
        <xs:complexContent>
          <xs:extension base="tipoMascota">
            <xs:sequence>
                <xs:element name="tiempoAparicion" minOccurs="0" type="tipoTiempoAparicion"/>
            </xs:sequence>
            <xs:attribute name="coloresRopa" type="listaColores"/>
            <xs:attribute name="matricula" type="tipoMatricula"/>          
          </xs:extension>
        </xs:complexContent>
      </xs:complexType>  
    

    <xs:simpleType name="coloresRGB">
        <xs:restriction base="xs:string">
            <xs:enumeration value="rojo"/>
            <xs:enumeration value="verde"/>
            <xs:enumeration value="azul"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="coloresBinarios">
        <xs:restriction base="xs:string">
            <xs:enumeration value="blanco"/>
            <xs:enumeration value="negro"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="unionColores">
        <xs:union memberTypes="coloresRGB coloresBinarios"/> 
    </xs:simpleType>

    <xs:simpleType name="listaColores">
        <xs:list itemType="unionColores"/>
    </xs:simpleType>

    <xs:complexType name="tipoPersonajes" mixed="true">
        <xs:sequence>
            <xs:element name="personaje" maxOccurs="unbounded" type="tipoPersonaje"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="tipoMatricula">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}[A-Z]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tipoTiempoAparicion">
        <xs:simpleContent>
          <xs:extension base="contenidoNumerico">
            <xs:attribute name="temporada" type="xs:string"/>
          </xs:extension>
        </xs:simpleContent>
      </xs:complexType>
    
    
      <xs:simpleType name="contenidoNumerico">
        <xs:restriction base="contenidoNumericoAmplio">
          <xs:minInclusive value="100"/>
          <xs:maxInclusive value="1000"/>
        </xs:restriction>
      </xs:simpleType>


      <xs:simpleType name="contenidoNumericoAmplio">
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="1"/>
          <xs:maxInclusive value="10000"/>
        </xs:restriction>
      </xs:simpleType>


    
    <xs:complexType name="tipoCapitulos">
        <xs:sequence>
            <xs:element name="capitulo" type="tipoCapitulo" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoCapitulo">
        <xs:choice>
            <xs:element name="temporada1" type="tipoVacio"/>
            <xs:element name="temporada2" type="tipoVacio"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="tipoVacio"></xs:complexType>
</xs:schema>

=== rafaelMunoz77/LMSGI_2022-23/Unidad_04_DTD_XSD/XSD/examen2017/simpsons.xml
<?xml version="1.0" encoding="UTF-8"?>
<simpsons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="simpsons.xsd">
    <personajes>Todos los de la serie
        <personaje nombre="Lisa" coloresRopa="rojo verde blanco">
            <tiempoAparicion temporada="">128</tiempoAparicion>
        </personaje>
        <personaje nombre="Homer" matricula="1234ABC"></personaje>
    </personajes>
    <capitulos>
        <capitulo>
            <temporada1/>            
        </capitulo>
        <capitulo>
            <temporada2/>
        </capitulo>
    </capitulos>
</simpsons>
