<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE superheroes [
  <!ELEMENT superheroes (superheroe*)>
  <!ELEMENT superheroe (poderes?, nombre?)*>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT poderes (poder*)>
  <!ELEMENT poder (#PCDATA)>
]>
<superheroes>
  <superheroe>
  	<nombre>Iron Man</nombre>
  	<poderes>
  		<poder></poder>
  		<poder></poder>
  		<poder>Armadura prodigiosa</poder>
  	</poderes>
  </superheroe>
</superheroes>