=== rafaelMunoz77/LMSGI_2022-23/Unidad_04_DTD_XSD/DTD/exámenes antiguos/DTD2018/Pokemon/pokemon.dtd
<!ELEMENT pokemon (#PCDATA | tipo | personaje | estadio)*>
<!ATTLIST pokemon creador CDATA #FIXED "Satoshi Tajiri">
<!ELEMENT tipo EMPTY>
<!ATTLIST tipo valor ID #REQUIRED>
<!ELEMENT personaje EMPTY>
<!ATTLIST personaje nombre CDATA #REQUIRED
                    color (rojo | azul | blanco | amarillo) "rojo"
                    tipo IDREF #IMPLIED>
<!ELEMENT estadio (tiposAdmitidos, fechaCreacion?, torneoJugado+, (activo | derruido))>
<!ELEMENT fechaCreacion (#PCDATA)>
<!ELEMENT torneoJugado (#PCDATA)>
<!ELEMENT activo EMPTY>
<!ELEMENT derruido EMPTY>
<!ELEMENT tiposAdmitidos EMPTY>
<!ATTLIST tiposAdmitidos tipos IDREFS #REQUIRED>

=== rafaelMunoz77/LMSGI_2022-23/Unidad_04_DTD_XSD/DTD/exámenes antiguos/DTD2018/Pokemon/pokemon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pokemon SYSTEM "pokemon.dtd">
<pokemon creador="Satoshi Tajiri">La mejor serie
    <tipo valor="electrico"/>
    <tipo valor="fuego"/>
    <personaje nombre="Pikachu" color="amarillo" tipo="electrico"/>
    <estadio>
        <tiposAdmitidos tipos="electrico fuego"/>
        <fechaCreacion>11 de agosto de 2011</fechaCreacion>
        <torneoJugado>Máster 1000</torneoJugado>
        <torneoJugado>Máster 10000</torneoJugado>
        <derruido />
    </estadio>
</pokemon>
