=== rafaelMunoz77/LMSGI_2022-23/Unidad_04_DTD_XSD/DTD/exámenes antiguos/DTD2020/examen.dtd
<!ELEMENT zodiaco (#PCDATA | signo | caballero)*>
<!ELEMENT signo EMPTY>
<!ELEMENT caballero (armadura?, fechaNacimiento, (batallaEpica | peleilla)+)>
<!ELEMENT armadura (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT batallaEpica (#PCDATA)>
<!ELEMENT peleilla (#PCDATA)>
<!ENTITY % caracteristicasComunes "nombre ID #REQUIRED">
<!ATTLIST signo elemento (agua | aire | fuego | tierra) "agua"
                %caracteristicasComunes;
                signoAfin IDREF #IMPLIED
                signosAmigos IDREFS #IMPLIED
                creo CDATA #FIXED "no">  
<!ATTLIST caballero %caracteristicasComunes;>

=== rafaelMunoz77/LMSGI_2022-23/Unidad_04_DTD_XSD/DTD/exámenes antiguos/DTD2020/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zodiaco SYSTEM "examen.dtd">
<zodiaco> Esta es la predicción de los signos del zodiaco
	<signo nombre="aries" elemento="agua" signoAfin="acuario" signosAmigos="piscis acuario" creo="no"></signo>
	<signo nombre="acuario" signoAfin="acuario" signosAmigos="piscis acuario"></signo>
	<signo nombre="leo" signoAfin="acuario" signosAmigos="piscis acuario"></signo>
	<signo nombre="libra" signoAfin="acuario" signosAmigos="piscis acuario"></signo>
	<signo nombre="piscis" signoAfin="acuario" signosAmigos="piscis acuario"></signo>
	<caballero nombre="Seiya">
		<armadura>Plata</armadura>
		<fechaNacimiento>asdf</fechaNacimiento>
		<batallaEpica>asdfa</batallaEpica>
	</caballero>
</zodiaco>
